<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gorilla VR Settings</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #121212;
            color: #ffffff;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 900px;
            margin: 40px auto;
            padding: 20px;
            background-color: #1e1e1e;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.5);
        }

        h1 {
            text-align: center;
            margin-bottom: 30px;
            font-size: 32px;
            color: #f9a825;
        }

        .section {
            margin-bottom: 40px;
        }

        .section h2 {
            font-size: 24px;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
            color: #fbc02d;
        }

        .setting {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 15px;
        }

        .setting label {
            font-size: 18px;
        }

        .setting input[type="checkbox"] {
            transform: scale(1.5);
        }

        .setting select,
        .setting input[type="range"] {
            padding: 5px;
            border-radius: 5px;
            border: 1px solid #333;
            background-color: #333;
            color: #fff;
        }

        .setting input[type="range"] {
            width: 200px;
        }

        .setting input[type="number"] {
            width: 60px;
            padding: 5px;
            border-radius: 5px;
            border: 1px solid #333;
            background-color: #333;
            color: #fff;
        }

        .save-button {
            width: 100%;
            padding: 15px;
            background-color: #f9a825;
            color: #121212;
            border: none;
            border-radius: 10px;
            font-size: 18px;
            cursor: pointer;
            margin-top: 20px;
        }

        .save-button:hover {
            background-color: #fbc02d;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Gorilla VR Settings</h1>

        <div class="section" id="general-settings">
            <h2>General Settings</h2>
            <div class="setting">
                <label for="username">Username:</label>
                <input type="text" id="username" placeholder="Enter your username">
            </div>
            <div class="setting">
                <label for="language">Language:</label>
                <select id="language">
                    <option value="en">English</option>
                    <option value="es">Spanish</option>
                    <option value="fr">French</option>
                    <option value="de">German</option>
                    <option value="jp">Japanese</option>
                </select>
            </div>
            <div class="setting">
                <label for="show-hints">Show Hints:</label>
                <input type="checkbox" id="show-hints" checked>
            </div>
        </div>

        <div class="section" id="video-settings">
            <h2>Video Settings</h2>
            <div class="setting">
                <label for="resolution">Resolution:</label>
                <select id="resolution">
                    <option value="1080p">1920x1080 (1080p)</option>
                    <option value="1440p">2560x1440 (1440p)</option>
                    <option value="4k">3840x2160 (4K)</option>
                </select>
            </div>
            <div class="setting">
                <label for="fullscreen">Fullscreen Mode:</label>
                <input type="checkbox" id="fullscreen" checked>
            </div>
            <div class="setting">
                <label for="fov">Field of View:</label>
                <input type="range" id="fov" min="70" max="120" value="90">
            </div>
            <div class="setting">
                <label for="v-sync">V-Sync:</label>
                <input type="checkbox" id="v-sync">
            </div>
        </div>

        <div class="section" id="audio-settings">
            <h2>Audio Settings</h2>
            <div class="setting">
                <label for="master-volume">Master Volume:</label>
                <input type="range" id="master-volume" min="0" max="100" value="80">
            </div>
            <div class="setting">
                <label for="music-volume">Music Volume:</label>
                <input type="range" id="music-volume" min="0" max="100" value="50">
            </div>
            <div class="setting">
                <label for="effects-volume">Effects Volume:</label>
                <input type="range" id="effects-volume" min="0" max="100" value="70">
            </div>
            <div class="setting">
                <label for="voice-chat">Enable Voice Chat:</label>
                <input type="checkbox" id="voice-chat" checked>
            </div>
        </div>

        <div class="section" id="control-settings">
            <h2>Control Settings</h2>
            <div class="setting">
                <label for="sensitivity">Sensitivity:</label>
                <input type="range" id="sensitivity" min="1" max="10" value="5">
            </div>
            <div class="setting">
                <label for="invert-y-axis">Invert Y-Axis:</label>
                <input type="checkbox" id="invert-y-axis">
            </div>
            <div class="setting">
                <label for="movement-speed">Movement Speed:</label>
                <input type="range" id="movement-speed" min="1" max="10" value="5">
            </div>
            <div class="setting">
                <label for="controller-layout">Controller Layout:</label>
                <select id="controller-layout">
                    <option value="default">Default</option>
                    <option value="custom">Custom</option>
                </select>
            </div>
        </div>

        <button class="save-button">Save Settings</button>
    </div>
</body>

</html>
